server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /tmp/positions.yaml

clients:
- url: https://${LOKI_TENANT_ID}:${LOKI_TOKEN}@${LOKI_HOST}/loki/api/v1/push

scrape_configs:
  - job_name: ${JOB_NAME}

    relabel_configs:
      - source_labels: ['__heroku_drain_host']
        target_label: 'host'
      - source_labels: ['__heroku_drain_app']
        target_label: 'app'
      - source_labels: ['__heroku_drain_proc']
        target_label: 'proc'

    heroku_drain:
      server:
        http_listen_address: 0.0.0.0
        http_listen_port: ${PORT}
        log_level: info
      labels:
        job: ${JOB_NAME}

